# Numpy Arrays 

In [1]:
import numpy as np

In [43]:
a = np.array([1,2,3])
print(a, a.dtype, a.shape, a.size, a.nbytes, a.ndim)

a2 = np.array([[1,2,3],[4,5,6]])
print(a2, a2.dtype, a2.shape, a2.size, a2.nbytes, a2.ndim)


[1 2 3] int64 (3,) 3 24 1
[[1 2 3]
 [4 5 6]] int64 (2, 3) 6 48 2


In [17]:
# array filled with zeros
b = np.zeros(3)
print(b, b.dtype)

[0. 0. 0.] float64


In [18]:
# array filled with ones
c = np.ones(3, dtype='int8')
print(c, c.dtype)

[1 1 1] int8


In [19]:
# array filled with a specific number
d = np.full(3, 6)
print(d, d.dtype)

[6 6 6] int64


In [33]:
# array with evenly spaced values between two numbers
e = np.linspace(1,10)
print(e)

print('---------------------------------------------------------')

e = np.linspace(1,10, num=25) # specififying the interval
print(e)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
---------------------------------------------------------
[ 1.     1.375  1.75   2.125  2.5    2.875  3.25   3.625  4.     4.375
  4.75   5.125  5.5    5.875  6.25   6.625  7.     7.375  7.75   8.125
  8.5    8.875  9.25   9.625 10.   ]


In [37]:
# identity matrix
f = np.eye(4)
print(f)

print('---------------------------------------------------------')

f = np.identity(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
---------------------------------------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [64]:
random = np.random.rand(4,4)
print(random)

[[2.57492425e-01 4.70432794e-01 9.93483756e-01 7.32139982e-01]
 [9.37474166e-01 1.92655398e-01 6.52248576e-01 1.48181346e-01]
 [3.73066449e-01 9.98550003e-01 1.46319411e-01 1.47047707e-01]
 [3.01779634e-01 8.72010098e-01 8.38473422e-01 2.15478268e-04]]


In [57]:
g = np.arange(6) # array with a range of values
print(g)

print('-----------')

g2 = np.reshape(g,(2,3)) # reshaping the array
print(g2)

print('-----------')

g3 = np.reshape(g,(3,2))
print(g3)

print('-----------')

print(np.reshape(g3, (6,)))

print('-----------')

print(np.reshape(g3, (6,1)))

[0 1 2 3 4 5]
-----------
[[0 1 2]
 [3 4 5]]
-----------
[[0 1]
 [2 3]
 [4 5]]
-----------
[0 1 2 3 4 5]
-----------
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [70]:
print(g2)
print('----')
print(np.transpose(g2))

[[0 1 2]
 [3 4 5]]
----
[[0 3]
 [1 4]
 [2 5]]


In [72]:
print(g3.flatten())

[0 1 2 3 4 5]


In [81]:
arr = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])

print(np.concatenate([arr,arr2]))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [82]:
arr = np.arange(9)
print(arr)

print(np.split(arr,3)) # split the array into 3 

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [99]:
arr = np.arange(9).reshape(3,3)
print(arr,'\n ----')

arr2 = np.arange(6).reshape(3,2)
print(arr2, '\n ----')

arr3 = np.arange(6).reshape(2,3)
print(arr3, '\n ----')

print('\n hstack:\n') # same no. of rows
print(np.hstack((arr,arr2)))

print('\n vstack:\n') # same no. of cols
print(np.vstack((arr,arr3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]] 
 ----
[[0 1]
 [2 3]
 [4 5]] 
 ----
[[0 1 2]
 [3 4 5]] 
 ----

 hstack:

[[0 1 2 0 1]
 [3 4 5 2 3]
 [6 7 8 4 5]]

 vstack:

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]]


In [112]:
arr = np.arange(9)
print(arr)
print(arr[1:5])
print(arr[:6])
print(arr[5:])
print(arr[:6:2])
print(arr[2:-2])

[0 1 2 3 4 5 6 7 8]
[1 2 3 4]
[0 1 2 3 4 5]
[5 6 7 8]
[0 2 4]
[2 3 4 5 6]


In [153]:
arr = np.array([4,5,2,6,0,3,7,8,3,1])
print(np.where(arr<=5))
print(np.where(arr<=5, arr, -1))
print(np.nonzero(arr))

(array([0, 1, 2, 4, 5, 8, 9]),)
[ 4  5  2 -1  0  3 -1 -1  3  1]
(array([0, 1, 2, 3, 5, 6, 7, 8, 9]),)


In [147]:
arr = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])

print('dot product: \n')
print(np.dot(arr,np.transpose(arr2)))
print('--')
print(np.dot(arr.T,arr2))

print('--')
print("Multiply: \n")
print(np.multiply(arr,arr2))

print('--')
print("Mean: \n")
print(np.mean(arr))

print('--')
print("Median: \n")
print(np.median(arr))

print('--')
print("Standard Deviation: \n")
print(np.std(arr))

print('--')
print("Variance: \n")
print(np.var(arr))

print('--')
print("Cumulative Sum: \n")
print(np.cumsum(arr))

print('--')
print("Elements Product: \n")
print(np.prod(arr))

dot product: 

[[ 50  68]
 [122 167]]
--
[[47 52 57]
 [64 71 78]
 [81 90 99]]
--
Multiply: 

[[ 7 16 27]
 [40 55 72]]
--
Mean: 

3.5
--
Median: 

3.5
--
Standard Deviation: 

1.707825127659933
--
Variance: 

2.9166666666666665
--
Cumulative Sum: 

[ 1  3  6 10 15 21]
--
Elements Product: 

720
